# Generated by Django 3.2.25 on 2024-06-04 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("faq", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FaqContent",
        ),
    ]
