# Generated by Django 3.2.25 on 2024-06-04 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='bag_total',
            new_name='grand_total',
        ),
    ]
