# Generated by Django 3.2.25 on 2024-06-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("user_msgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usermessage",
            name="receiver",
            field=models.ManyToManyField(
                related_name="message_receiver", to="users.UserProfile"
            ),
        ),
    ]
