# Generated by Django 3.2.25 on 2024-05-16 21:01

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_msgs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usermessage',
            name='puzzle_photo',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
