# Generated by Django 3.2.25 on 2024-06-12 19:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_msgs', '0002_usermessage_puzzle_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usermessage',
            name='puzzle_photo',
        ),
    ]
