# Generated by Django 3.2.25 on 2024-06-16 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contact_us", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactus",
            name="msg_content",
            field=models.TextField(blank=True, max_length=240, null=True),
        ),
    ]
