# Generated by Django 3.2.25 on 2024-05-14 22:42

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PuzzleExchange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_title', models.CharField(max_length=200, unique=True)),
                ('submitted_on', models.DateTimeField(auto_now=True)),
                ('approved_submission', models.BooleanField(default=False)),
                ('submission_text', models.TextField()),
                ('puzzle_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzle_submission', to='users.userprofile')),
            ],
        ),
    ]
