# Generated by Django 3.2.25 on 2024-06-12 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puzzle_exchange', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='puzzleexchange',
            old_name='submission_text',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='puzzleexchange',
            old_name='puzzle_image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='puzzleexchange',
            old_name='submission_title',
            new_name='title',
        ),
    ]
