# Generated by Django 3.2.25 on 2024-06-10 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_remove_product_image_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
